### ISSUE TITLE
Docker image `docker.vectorized.io/vectorized/redpanda` not public anymore

### ISSUE THREAD

**Issue by klaus993** [redpanda-data/github-action#1]
Hello there!

We're using Redpanda in our CI (GitHub Actions workflow) using what's in this repo, like it's mentioned in [this post](https://redpanda.com/blog/github-actions-testing-redpanda-development#Continuous-Integration), like so:

```yaml
steps:
  - name: start Redpanda
          uses: Redpanda-data/github-action@v0.1.3
          with:
          version: "latest"
```

And starting today, we are getting this error when that step of the workflow is executed:
```
> Run Redpanda-data/github-action@v0.1.3
Unable to find image 'docker.vectorized.io/vectorized/redpanda:latest' locally
docker: Error response from daemon: unauthorized: authentication required.
See 'docker run --help'.
```

We replaced the `job` mentioned earlier (`start Redpanda`) with this `service`:
```yaml
services:
  redpanda:
    image: vectorized/redpanda:latest
    ports:
      - 8081:8081
      - 9092:9092
```
And this works fine since it's using the image from the Docker Hub.

Just wanted to report that using `Redpanda-data/github-action@v0.1.3` is completely broken and unusable now. Is there a reason behind making the image private? Or this was a mistake?

Thanks.

**Comment by klaus993** [comment]
cc @fernandes @emaxerrno

**Comment by klaus993** [comment]
FYI @fernandes @RodolfoSilva I just performed a local `docker pull docker.vectorized.io/vectorized/redpanda:latest` and it's fixed now. But I guess that keeping it pointed to Docker Hub is wiser?

**Comment by RodolfoSilva** [comment]
I think we can receive the container registry as a parameter, and use by default the vectorized container registry. Maybe something like this:

```yaml
steps:
  - name: start Redpanda
    uses: Redpanda-data/github-action@v0.1.3
    with:
      image: "docker.vectorized.io/vectorized/redpanda"
      version: "latest"
```
